# Generated by Django 3.1 on 2020-09-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Designations',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.designation'),
        ),
    ]
