# Generated by Django 3.1 on 2020-09-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20200903_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Access_Level',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Partner',
            },
        ),
        migrations.CreateModel(
            name='Partner_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authApp.facility')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Partner_Facility',
            },
        ),
    ]
