# Generated by Django 3.1 on 2020-09-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_access_level_partner_partner_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authApp.access_level'),
        ),
    ]
