# Generated by Django 3.1 on 2020-09-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_users_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.designation'),
        ),
        migrations.AlterField(
            model_name='users',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.facility'),
        ),
    ]
