# Generated by Django 3.1 on 2020-09-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_auto_20200914_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner_facility',
            name='user',
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
