# Generated by Django 3.1 on 2020-09-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_auto_20200914_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner_facility',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
