# Generated by Django 3.1 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20200922_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partner_facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partner_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
