# Generated by Django 3.1 on 2020-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='open_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
