# Generated by Django 3.1 on 2020-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
