# Generated by Django 3.1 on 2020-09-10 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_response_open_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='active_till',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
