# Generated by Django 3.1 on 2020-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_answer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
