# Generated by Django 3.1 on 2020-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200917_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
