# Generated by Django 3.1 on 2020-09-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200915_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccc_number', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=30)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionnaire')),
            ],
            options={
                'db_table': 'End_Questionnaire',
            },
        ),
    ]
