# Generated by Django 3.1 on 2020-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200915_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
