name: deploy to test instance
on:
  push:
    branches: [dev]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd  /apps/github-workflows/mhealth-apps/
          sudo rm -rf psurvey_api
          sudo mkdir psurvey_api
          sudo chown -R cicd2:cicd2 psurvey_api
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/psurvey_api    
          cd psurvey_api/
          git clone -b dev https://github.com/palladiumkenya/psurvey_api.git .
          git status
          cp  /apps/dockerApps/psurvey_api/python.dockerfile /apps/github-workflows/mhealth-apps/psurvey_api
          cp  /apps/dockerApps/psurvey_api/nginx.dockerfile /apps/github-workflows/mhealth-apps/psurvey_api
          cp  /apps/dockerApps/psurvey_api/docker-compose.yml /apps/github-workflows/mhealth-apps/psurvey_api
          cp -r /apps/dockerApps/psurvey_api/docker/ /apps/github-workflows/mhealth-apps/psurvey_api
          cp /apps/dockerApps/psurvey_api/.env /apps/github-workflows/mhealth-apps/psurvey_api/
          docker-compose stop pythonpsurvey
          docker-compose rm -f pythonpsurvey
          docker-compose up -d --build pythonpsurvey
